# Get the base image for Python 3.12 alpine version
FROM python:3.12-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY report.py .

# Install any dependencies specified in the requirements file
CMD ["python", "report.py"]